using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;
using System;

public class MainManuControlScript : MonoBehaviour {

	public Button levelButton02, levelButton03, levelButton04, levelButton05, levelButton06, levelButton07, levelButton08, levelButton09, levelButton10, levelButton11, levelButton12, levelButton13, levelButton14, levelButton15, levelButton16, levelButton17, levelButton18, levelButton19, levelButton20, levelButton21, levelButton22, levelButton23, levelButton24, levelButton25, levelButton26, levelButton27, levelButton28, levelButton29, levelButton30, levelButton31, levelButton32, levelButton33;
	int levelPassed;

	// Use this for initialization
	void Start () {
		levelPassed = PlayerPrefs.GetInt ("LevelPassed");

		levelButton02.interactable = false;
		levelButton03.interactable = false;
		levelButton04.interactable = false;
		levelButton05.interactable = false;
		levelButton06.interactable = false;
		levelButton07.interactable = false;
		levelButton08.interactable = false;
		levelButton09.interactable = false;
		levelButton10.interactable = false;
		levelButton11.interactable = false;
		levelButton12.interactable = false;
		levelButton13.interactable = false;
		levelButton14.interactable = false;
		levelButton15.interactable = false;
		levelButton16.interactable = false;
		levelButton17.interactable = false;
		levelButton18.interactable = false;
		levelButton19.interactable = false;
		levelButton20.interactable = false;
		levelButton21.interactable = false;
		levelButton22.interactable = false;
		levelButton23.interactable = false;
		levelButton24.interactable = false;
		levelButton25.interactable = false;
		levelButton26.interactable = false;
		levelButton27.interactable = false;
		levelButton28.interactable = false;
		levelButton29.interactable = false;
		levelButton30.interactable = false;
		levelButton31.interactable = false;
		levelButton32.interactable = false;
		levelButton33.interactable = false;
		switch (levelPassed) {
		case 1:
			levelButton02.interactable = true;
			break;
		case 2:
			levelButton02.interactable = true;
			levelButton03.interactable = true;
			break;
		case 3:
			levelButton02.interactable = true;
			levelButton03.interactable = true;
			levelButton04.interactable = true;
			break;
			case 4:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				break;
			case 5:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				break;
			case 6:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				break;
			case 7:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				break;
			case 8:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				break;
			case 9:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				break;
			case 10:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				levelButton11.interactable = true;
				break;
			case 11:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				levelButton11.interactable = true;
				levelButton12.interactable = true;
				break;
			case 12:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				levelButton11.interactable = true;
				levelButton12.interactable = true;
				levelButton13.interactable = true;
				break;
			case 13:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				levelButton11.interactable = true;
				levelButton12.interactable = true;
				levelButton13.interactable = true;
				levelButton14.interactable = true;
				break;
			case 14:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				levelButton11.interactable = true;
				levelButton12.interactable = true;
				levelButton13.interactable = true;
				levelButton14.interactable = true;
				levelButton15.interactable = true;
				break;
			case 15:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				levelButton11.interactable = true;
				levelButton12.interactable = true;
				levelButton13.interactable = true;
				levelButton14.interactable = true;
				levelButton15.interactable = true;
				levelButton16.interactable = true;
				break;
			case 16:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				levelButton11.interactable = true;
				levelButton12.interactable = true;
				levelButton13.interactable = true;
				levelButton14.interactable = true;
				levelButton15.interactable = true;
				levelButton16.interactable = true;
				levelButton17.interactable = true;
				break;
			case 17:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				levelButton11.interactable = true;
				levelButton12.interactable = true;
				levelButton13.interactable = true;
				levelButton14.interactable = true;
				levelButton15.interactable = true;
				levelButton16.interactable = true;
				levelButton17.interactable = true;
				levelButton18.interactable = true;
				break;
			case 18:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				levelButton11.interactable = true;
				levelButton12.interactable = true;
				levelButton13.interactable = true;
				levelButton14.interactable = true;
				levelButton15.interactable = true;
				levelButton16.interactable = true;
				levelButton17.interactable = true;
				levelButton18.interactable = true;
				levelButton19.interactable = true;
				break;
			case 19:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				levelButton11.interactable = true;
				levelButton12.interactable = true;
				levelButton13.interactable = true;
				levelButton14.interactable = true;
				levelButton15.interactable = true;
				levelButton16.interactable = true;
				levelButton17.interactable = true;
				levelButton18.interactable = true;
				levelButton19.interactable = true;
				levelButton20.interactable = true;
				break;
			case 20:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				levelButton11.interactable = true;
				levelButton12.interactable = true;
				levelButton13.interactable = true;
				levelButton14.interactable = true;
				levelButton15.interactable = true;
				levelButton16.interactable = true;
				levelButton17.interactable = true;
				levelButton18.interactable = true;
				levelButton19.interactable = true;
				levelButton20.interactable = true;
				levelButton21.interactable = true;
				break;
			case 21:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				levelButton11.interactable = true;
				levelButton12.interactable = true;
				levelButton13.interactable = true;
				levelButton14.interactable = true;
				levelButton15.interactable = true;
				levelButton16.interactable = true;
				levelButton17.interactable = true;
				levelButton18.interactable = true;
				levelButton19.interactable = true;
				levelButton20.interactable = true;
				levelButton21.interactable = true;
				levelButton22.interactable = true;
				break;
			case 22:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				levelButton11.interactable = true;
				levelButton12.interactable = true;
				levelButton13.interactable = true;
				levelButton14.interactable = true;
				levelButton15.interactable = true;
				levelButton16.interactable = true;
				levelButton17.interactable = true;
				levelButton18.interactable = true;
				levelButton19.interactable = true;
				levelButton20.interactable = true;
				levelButton21.interactable = true;
				levelButton22.interactable = true;
				levelButton23.interactable = true;
				break;
			case 23:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				levelButton11.interactable = true;
				levelButton12.interactable = true;
				levelButton13.interactable = true;
				levelButton14.interactable = true;
				levelButton15.interactable = true;
				levelButton16.interactable = true;
				levelButton17.interactable = true;
				levelButton18.interactable = true;
				levelButton19.interactable = true;
				levelButton20.interactable = true;
				levelButton21.interactable = true;
				levelButton22.interactable = true;
				levelButton23.interactable = true;
				levelButton24.interactable = true;
				break;
			case 24:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				levelButton11.interactable = true;
				levelButton12.interactable = true;
				levelButton13.interactable = true;
				levelButton14.interactable = true;
				levelButton15.interactable = true;
				levelButton16.interactable = true;
				levelButton17.interactable = true;
				levelButton18.interactable = true;
				levelButton19.interactable = true;
				levelButton20.interactable = true;
				levelButton21.interactable = true;
				levelButton22.interactable = true;
				levelButton23.interactable = true;
				levelButton24.interactable = true;
				levelButton25.interactable = true;
				break;
			case 25:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				levelButton11.interactable = true;
				levelButton12.interactable = true;
				levelButton13.interactable = true;
				levelButton14.interactable = true;
				levelButton15.interactable = true;
				levelButton16.interactable = true;
				levelButton17.interactable = true;
				levelButton18.interactable = true;
				levelButton19.interactable = true;
				levelButton20.interactable = true;
				levelButton21.interactable = true;
				levelButton22.interactable = true;
				levelButton23.interactable = true;
				levelButton24.interactable = true;
				levelButton25.interactable = true;
				levelButton26.interactable = true;
				break;
			case 26:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				levelButton11.interactable = true;
				levelButton12.interactable = true;
				levelButton13.interactable = true;
				levelButton14.interactable = true;
				levelButton15.interactable = true;
				levelButton16.interactable = true;
				levelButton17.interactable = true;
				levelButton18.interactable = true;
				levelButton19.interactable = true;
				levelButton20.interactable = true;
				levelButton21.interactable = true;
				levelButton22.interactable = true;
				levelButton23.interactable = true;
				levelButton24.interactable = true;
				levelButton25.interactable = true;
				levelButton26.interactable = true;
				levelButton27.interactable = true;
				break;
			case 27:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				levelButton11.interactable = true;
				levelButton12.interactable = true;
				levelButton13.interactable = true;
				levelButton14.interactable = true;
				levelButton15.interactable = true;
				levelButton16.interactable = true;
				levelButton17.interactable = true;
				levelButton18.interactable = true;
				levelButton19.interactable = true;
				levelButton20.interactable = true;
				levelButton21.interactable = true;
				levelButton22.interactable = true;
				levelButton23.interactable = true;
				levelButton24.interactable = true;
				levelButton25.interactable = true;
				levelButton26.interactable = true;
				levelButton27.interactable = true;
				levelButton28.interactable = true;
				break;
			case 28:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				levelButton11.interactable = true;
				levelButton12.interactable = true;
				levelButton13.interactable = true;
				levelButton14.interactable = true;
				levelButton15.interactable = true;
				levelButton16.interactable = true;
				levelButton17.interactable = true;
				levelButton18.interactable = true;
				levelButton19.interactable = true;
				levelButton20.interactable = true;
				levelButton21.interactable = true;
				levelButton22.interactable = true;
				levelButton23.interactable = true;
				levelButton24.interactable = true;
				levelButton25.interactable = true;
				levelButton26.interactable = true;
				levelButton27.interactable = true;
				levelButton28.interactable = true;
				levelButton29.interactable = true;
				break;
			case 29:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				levelButton11.interactable = true;
				levelButton12.interactable = true;
				levelButton13.interactable = true;
				levelButton14.interactable = true;
				levelButton15.interactable = true;
				levelButton16.interactable = true;
				levelButton17.interactable = true;
				levelButton18.interactable = true;
				levelButton19.interactable = true;
				levelButton20.interactable = true;
				levelButton21.interactable = true;
				levelButton22.interactable = true;
				levelButton23.interactable = true;
				levelButton24.interactable = true;
				levelButton25.interactable = true;
				levelButton26.interactable = true;
				levelButton27.interactable = true;
				levelButton28.interactable = true;
				levelButton29.interactable = true;
				levelButton30.interactable = true;
				break;
			case 30:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				levelButton11.interactable = true;
				levelButton12.interactable = true;
				levelButton13.interactable = true;
				levelButton14.interactable = true;
				levelButton15.interactable = true;
				levelButton16.interactable = true;
				levelButton17.interactable = true;
				levelButton18.interactable = true;
				levelButton19.interactable = true;
				levelButton20.interactable = true;
				levelButton21.interactable = true;
				levelButton22.interactable = true;
				levelButton23.interactable = true;
				levelButton24.interactable = true;
				levelButton25.interactable = true;
				levelButton26.interactable = true;
				levelButton27.interactable = true;
				levelButton28.interactable = true;
				levelButton29.interactable = true;
				levelButton30.interactable = true;
				levelButton31.interactable = true;
				break;
			case 31:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				levelButton11.interactable = true;
				levelButton12.interactable = true;
				levelButton13.interactable = true;
				levelButton14.interactable = true;
				levelButton15.interactable = true;
				levelButton16.interactable = true;
				levelButton17.interactable = true;
				levelButton18.interactable = true;
				levelButton19.interactable = true;
				levelButton20.interactable = true;
				levelButton21.interactable = true;
				levelButton22.interactable = true;
				levelButton23.interactable = true;
				levelButton24.interactable = true;
				levelButton25.interactable = true;
				levelButton26.interactable = true;
				levelButton27.interactable = true;
				levelButton28.interactable = true;
				levelButton29.interactable = true;
				levelButton30.interactable = true;
				levelButton31.interactable = true;
				levelButton32.interactable = true;
				break;
			case 32:
				levelButton02.interactable = true;
				levelButton03.interactable = true;
				levelButton04.interactable = true;
				levelButton05.interactable = true;
				levelButton06.interactable = true;
				levelButton07.interactable = true;
				levelButton08.interactable = true;
				levelButton09.interactable = true;
				levelButton10.interactable = true;
				levelButton11.interactable = true;
				levelButton12.interactable = true;
				levelButton13.interactable = true;
				levelButton14.interactable = true;
				levelButton15.interactable = true;
				levelButton16.interactable = true;
				levelButton17.interactable = true;
				levelButton18.interactable = true;
				levelButton19.interactable = true;
				levelButton20.interactable = true;
				levelButton21.interactable = true;
				levelButton22.interactable = true;
				levelButton23.interactable = true;
				levelButton24.interactable = true;
				levelButton25.interactable = true;
				levelButton26.interactable = true;
				levelButton27.interactable = true;
				levelButton28.interactable = true;
				levelButton29.interactable = true;
				levelButton30.interactable = true;
				levelButton31.interactable = true;
				levelButton32.interactable = true;
				levelButton33.interactable = true;
				break;

		}
	}
	private void Update()
	{
		Debug.Log("otilgan bosqichlar soni "+levelPassed);
	}
	public void levelToLoad (int level)
	{
		SceneManager.LoadScene (level);
	}

	public void resetPlayerPrefs()
	{
		levelButton02.interactable = false;
		levelButton03.interactable = false;
		levelButton04.interactable = false;
		levelButton05.interactable = false;
		levelButton06.interactable = false;
		levelButton07.interactable = false;
		levelButton08.interactable = false;
		levelButton09.interactable = false;
		levelButton10.interactable = false;
		levelButton11.interactable = false;
		levelButton12.interactable = false;
		levelButton13.interactable = false;
		levelButton14.interactable = false;
		levelButton15.interactable = false;
		levelButton16.interactable = false;
		levelButton17.interactable = false;
		levelButton18.interactable = false;
		levelButton19.interactable = false;
		levelButton20.interactable = false;
		levelButton21.interactable = false;
		levelButton22.interactable = false;
		levelButton23.interactable = false;
		levelButton24.interactable = false;
		levelButton25.interactable = false;
		levelButton26.interactable = false;
		levelButton27.interactable = false;
		levelButton28.interactable = false;
		levelButton29.interactable = false;
		levelButton30.interactable = false;
		levelButton31.interactable = false;
		levelButton32.interactable = false;
		levelButton33.interactable = false;
		PlayerPrefs.DeleteAll ();
	}
}
